log: True
save_path: "/glade/work/kdagon/s2sml/results_wk3_608/" # change path

pbs:
  jobs: 10
  ##kernel: "ncar_pylib /glade/work/$USER/py37" # comment out
  bash: ["module load conda/latest; conda activate s2sml-env"] # conda env
  batch:
    N: "s2smlwk3"
    l: ["select=1:ncpus=4:ngpus=4:mem=30GB", "walltime=12:00:00"] # resource request
    A: "ACGD0007"
    q: "main"
    o: "/glade/work/kdagon/s2sml/results_wk3_608/out" # out path
    e: "/glade/work/kdagon/s2sml/results_wk3_608/err" # err path
    
optuna:
  storage: "s2s.db"
  study_name: "vanilla"
  storage_type: "sqlite"
  objective: "/glade/work/kdagon/s2sml/applications/train_multi.py" # train script
  direction: ["minimize", "minimize", "minimize"] # directions
  metric: ["valid_mae", "vmse_extreme_outp", "vcorr_cust"] # metrics
  n_trials: 1000
  gpu: True
  sampler:
    type: "MOTPESampler"
    n_startup_trials: 100
  parameters:
    optimizer:learning_rate:
      type: "loguniform"
      settings:
        name: "learning_rate"
        low: 1.0e-06
        high: 1.0e-02
    #data:norm: # comment out norm options
    #  type: "categorical"
    #  settings:
    #    name: "norm"
    #    choices: ["None", "minmax", "negone", "zscore"]
    trainer:weight_decay:
      type: "loguniform"
      settings:
        name: "weight_decay"
        low: 1.0e-12
        high: 1.0e-03
    trainer:train_batch_size:
      type: "int"
      settings:
        name: "train_batch_size"
        low: 4
        high: 128 # changed high batch size
    trainer:training_loss:
      type: "categorical"
      settings:
        name: "training_loss"
        choices: ["mae", "mse", "smooth", "logcosh", "xtanh", "xsigmoid", "huber"]
    model:name:
      type: "categorical"
      settings:
        name: "model_name"
        choices: ["unet", "unet++", "manet", "linknet", "fpn", "pspnet", "deeplabv3", "deeplabv3+"] # remove pan model
    #model:encoder_name: # comment out encoders
    #  type: "categorical"
    #  settings:
    #    name: "encoder_name"
    #    choices: ["resnet18", "resnet152", "densenet121", "xception", "efficientnet-b0", "mobilenet_v2", "dpn68", "vgg11"]
