seed: 1000
save_loc: "/glade/work/kdagon/s2sml/results_wk3_608/echo_opt" # changed path
img_gen: True # turn on imshow plots
scatter_gen: True # turn on scatter plots
# images generated every other img_iter (don't make zero! 'epoch divisible by')
# e.g., make 1 if image wanted every epoch; 5 if every fifth epoch, etc.
img_iter: 5 # make divisible by # epochs
callback_metric: ["valid_mae", "vmse_extreme_outp", "vcorr_cust"] # metrics
callback_direction: ["min", "min", "min"] # directions

data:
    homedir: '/glade/derecho/scratch/molina/' # data dir
    var: "tas2m" # variable
    wks: 3 # week
    dxdy: 31  # dxdy-1 
    lon0: 280.0 # SH
    lat0: -55 # SH
    norm: "minmax"

# transforms:
# #     training:
# #         RandomVerticalFlip:
# #             rate: 0.5
# #         RandomHorizontalFlip: 
# #             rate: 0.5
# #         Normalize:
# #             mode: 'sym'
# #         ToTensor: True
# #     validation:
# #         Normalize:
# #             mode: 'sym'
# #         ToTensor: True
# #     inference:
# #         Normalize:
# #             mode: 'sym'
#
model:
    name: "unet"
    #encoder_name: "resnet18" # comment out
    #encoder_weights: "imagenet" # comment out
    #decoder_attention_type: "scse" # comment out
    in_channels: 4
    classes: 1
    activation: "sigmoid" 
    
optimizer:
    learning_rate: 0.001
    weight_decay: 0.0
    
trainer:
    epochs: 75 # num epochs
    train_batch_size: 32
    valid_batch_size: 32
    batches_per_epoch: 100 # batches
    lr_patience: 2
    stopping_patience: 5
    loss: "smooth"
    metric: "valid_mae" # metric
    direction: "minimize" # add direction
