name: s2sml-analysis
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - cartopy=0.21.1
  - dask=2023.3.2
  - ipykernel=6.22.0
  - jupyter=1.0.0
  - jupyterlab=3.5.3
  - matplotlib=3.7.1
  - netcdf4=1.6.0
  - plotly=5.14.1
  - python=3.10.9
  - xarray=2023.3.0
  - xesmf=0.7.1
  - xskillscore=0.0.24
  - scipy=1.9.1
  - scikit-learn=1.1.2
  - properscoring=0.1